"""Train a custom wake word model using openWakeWord.

Validates input samples, generates negative examples, creates a
training configuration YAML, and prints instructions for running
the actual openWakeWord training pipeline.
"""

from __future__ import annotations

import argparse
import struct
import sys
import wave
from pathlib import Path

SAMPLE_RATE = 16000
SAMPLE_WIDTH = 2
NUM_CHANNELS = 1
NEGATIVE_SAMPLE_COUNT = 50
NEGATIVE_DURATION_SECONDS = 1.5
MIN_POSITIVE_SAMPLES = 5
CONFIG_FILENAME = "training_config.yaml"


def main() -> None:
    """Entry point: parse args and run the training preparation pipeline."""
    args = _parse_args()
    samples_dir = Path(args.samples_dir)
    output_dir = Path(args.output_dir)

    _validate_samples(samples_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    negative_dir = output_dir / "negative_samples"
    negative_dir.mkdir(exist_ok=True)
    generate_negative_samples(negative_dir, NEGATIVE_SAMPLE_COUNT)

    config_path = _create_training_config(
        word=args.word,
        samples_dir=samples_dir,
        negative_dir=negative_dir,
        output_dir=output_dir,
    )

    _print_instructions(args.word, config_path, output_dir)


def _parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns:
        Parsed argument namespace.
    """
    parser = argparse.ArgumentParser(
        description="Prepare custom wake word training for openWakeWord.",
    )
    parser.add_argument(
        "--word",
        required=True,
        help="The wake word text (e.g., 'Hey Vox').",
    )
    parser.add_argument(
        "--samples-dir",
        required=True,
        help="Directory containing positive WAV samples of the wake word.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory to save the training config and model output.",
    )
    return parser.parse_args()


def _validate_samples(samples_dir: Path) -> None:
    """Validate that the samples directory exists and has enough WAV files.

    Args:
        samples_dir: Path to the directory of positive WAV samples.

    Raises:
        SystemExit: If the directory is missing or has too few samples.
    """
    if not samples_dir.is_dir():
        print(f"Error: samples directory not found: {samples_dir}", file=sys.stderr)
        sys.exit(1)

    wav_files = list(samples_dir.glob("*.wav"))
    if len(wav_files) < MIN_POSITIVE_SAMPLES:
        print(
            f"Error: need at least {MIN_POSITIVE_SAMPLES} WAV samples, "
            f"found {len(wav_files)} in {samples_dir}",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Found {len(wav_files)} positive samples in {samples_dir}")


def generate_negative_samples(output_dir: Path, count: int = NEGATIVE_SAMPLE_COUNT) -> list[Path]:
    """Generate silent WAV files as negative training examples.

    Args:
        output_dir: Directory to write the silent WAV files into.
        count: Number of negative samples to generate.

    Returns:
        List of paths to the generated WAV files.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    num_frames = int(SAMPLE_RATE * NEGATIVE_DURATION_SECONDS)
    silence = struct.pack(f"<{num_frames}h", *([0] * num_frames))

    generated: list[Path] = []
    for i in range(count):
        path = output_dir / f"silence_{i:04d}.wav"
        _write_wav(path, silence)
        generated.append(path)

    print(f"Generated {count} negative (silent) samples in {output_dir}")
    return generated


def _write_wav(path: Path, raw_pcm: bytes) -> None:
    """Write raw PCM data to a WAV file.

    Args:
        path: Output file path.
        raw_pcm: Raw PCM audio bytes (16-bit signed LE).
    """
    with wave.open(str(path), "wb") as wf:
        wf.setnchannels(NUM_CHANNELS)
        wf.setsampwidth(SAMPLE_WIDTH)
        wf.setframerate(SAMPLE_RATE)
        wf.writeframes(raw_pcm)


def _create_training_config(
    *,
    word: str,
    samples_dir: Path,
    negative_dir: Path,
    output_dir: Path,
) -> Path:
    """Create a YAML training configuration for openWakeWord.

    Args:
        word: The wake word text.
        samples_dir: Path to positive audio samples.
        negative_dir: Path to generated negative samples.
        output_dir: Path for model output.

    Returns:
        Path to the written YAML config file.
    """
    config_content = f"""\
# openWakeWord training configuration
# Generated by VoxAgent train_wake_word.py

wake_word: "{word}"

positive_samples:
  directory: "{samples_dir.resolve()}"
  format: wav
  sample_rate: {SAMPLE_RATE}

negative_samples:
  directory: "{negative_dir.resolve()}"
  format: wav
  sample_rate: {SAMPLE_RATE}

training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  validation_split: 0.2
  early_stopping_patience: 10

model:
  architecture: "dnn"
  feature_type: "melspectrogram"
  n_mels: 40
  window_size_ms: 30
  hop_size_ms: 10

output:
  directory: "{output_dir.resolve()}"
  model_name: "{word.lower().replace(' ', '_')}_model"
"""

    config_path = output_dir / CONFIG_FILENAME
    config_path.write_text(config_content, encoding="utf-8")
    print(f"Training config written to {config_path}")
    return config_path


def _print_instructions(word: str, config_path: Path, output_dir: Path) -> None:
    """Print step-by-step instructions for running the actual training.

    Args:
        word: The wake word text.
        config_path: Path to the generated YAML config.
        output_dir: Path where model output will be saved.
    """
    model_name = word.lower().replace(" ", "_")
    print(
        f"""
{'=' * 60}
  Wake Word Training Preparation Complete
{'=' * 60}

Wake word: "{word}"
Config:    {config_path}
Output:    {output_dir}

Next steps to train the model:

  1. Install openWakeWord with training dependencies:
     pip install openwakeword[training]

  2. Run the training script:
     python -m openwakeword.train \\
       --config "{config_path}"

  3. After training, copy the .onnx model to VoxAgent:
     cp "{output_dir / f'{model_name}_model.onnx'}" \\
       models/wake_word/

  4. Update VoxAgent config to use the new wake word:
     wake_word_model: "models/wake_word/{model_name}_model.onnx"

For more information, see:
  https://github.com/dscripka/openWakeWord
{'=' * 60}
"""
    )


if __name__ == "__main__":
    main()
